# Generated by Django 5.1.5 on 2025-02-03 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_floorplan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='layout_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='plan_name',
            field=models.CharField(default='My Floor Plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
